name: Build Windows Executable

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6
        shell: pwsh

      - name: Verify Repository Structure
        run: |
          echo "Listing current directory contents:"
          Get-ChildItem -Recurse
        shell: pwsh

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed --name clock clock.py
        shell: pwsh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clock-executable
          path: dist/clock.exe