name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Display Directory Structure (Debugging)
        run: tree /F /A

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r smhos/requirements.txt  # Ensure all dependencies are installed

      - name: Build Executable
        run: |
          cd smhos  # Change to the correct directory
          pyinstaller --onefile --windowed --name TimerApp clock.py

      - name: Verify Build Output (Debugging)
        run: dir smhos\dist

      - name: Upload Executable
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: TimerApp
          path: smhos/dist/TimerApp.exe  # Ensure correct path